macro(shared_or_static target)

  if(NOT DEFINED BUILD_SHARED_LIBS AND NOT DEFINED ${target}_BUILD_SHARED_LIBS)
    set(${target}_LIBRARY_TYPE "")
  elseif(NOT DEFINED ${target}_BUILD_SHARED_LIBS)
    if(BUILD_SHARED_LIBS)
      set(${target}_LIBRARY_TYPE SHARED)
    else()
      set(${target}_LIBRARY_TYPE STATIC)
    endif()
  else()
    if(${target}_BUILD_SHARED)
      set(${target}_LIBRARY_TYPE SHARED)
    else()
      set(${target}_LIBRARY_TYPE STATIC)
    endif()
  endif()

endmacro()
